version: "2"

services:
    app:
      build: .
      ports:
        - "8080:8080"
    #web:
      #image: nginx
      #links:
        #- app
      #ports:
        #- "80:80"
      #volumes:
        #- ./nginx-app.conf:/etc/nginx/conf.d/default.conf

 
